### ISSUE TITLE
sqlite example error

### ISSUE THREAD

**Issue by zorrosopc** [shadow-node/ffi#7]
only get 1 column：

`for (var i = 0; i < cols; i++) {
    var colName = ffi.Types.castToJSType('string', colv)
    var colData = ffi.Types.castToJSType('string', argv)
    obj[colName] = colData
}`

**Comment by legendecas** [comment]
Hi, could you please give an output of the sqlite example that you think it's going wrong? which would greatly help us understand what issue you've encountered. :)

**Comment by zorrosopc** [comment]
I guess i fixed it:

```
JS_FUNCTION(DerefStringPointer)
{
  byte *ptr = unwrap_ptr_from_jbuffer(JS_GET_ARG(0, object));
  int offset = (int)JS_GET_ARG_IF_EXIST_OR_DEFAULT(1, number, 0);

  jerry_char_t **data_ptr = (jerry_char_t **)(ptr);/// fixbug: (jerry_char_t **)(ptr+offset)
  jerry_char_t *str_ptr = data_ptr[offset];/// fixbug: *data_ptr;

  return jerry_create_string(str_ptr);
}
```

**Comment by yorkie** [comment]
Hi @zorrosopc, may I ask you to create a Pull Request for your fix?
